// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oglbkfaxebibzjzhwzgr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nbGJrZmF4ZWJpYnpqemh3emdyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTI5NzcsImV4cCI6MjA3MDAyODk3N30.EsdoE6KowGJhZqyaPnr0fQhCQSeQibeUihNIohF3fUA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});